#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 23 01:58:41 2019

@author: tsc
"""

Sehir = input("Lütfen bulunduğunuz ili giriniz")
Dogum_tarihi = int(input("Lütfen doğum tarihini giriniz"))
a = str(Dogum_tarihi)
b= a[2:]
print("Yeni Oluşturulan Şifreniz"+" "+Sehir+b)
